# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up R environment with required versions
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Step 3: Set up Pandoc (required by pkgdown)
      - uses: r-lib/actions/setup-pandoc@v2

      # Step 4: Install necessary dependencies for pkgdown
      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_cran('pkgdown')
          remotes::install_deps(dependencies = TRUE)

      # Step 5: Build the pkgdown site
      - name: Build pkgdown site
        run: |
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: true  # Ensures the gh-pages branch is cleaned before deploying new files
          branch: gh-pages  # The branch where GitHub Pages is deployed from
          folder: docs      # The folder containing the built pkgdown site
