# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: pkgdown

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_cran("pkgdown")'
          R -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Build pkgdown site
        run: R -e 'pkgdown::build_site()'

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
